import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'signInTitle': 'Let’s sign you in',
          'signUpTitle': 'Let’s sign up',
          'signInButton': 'Login',
          'email': 'Email',
          'passwrod': 'Password',
          'signup': 'Sign up',
          'signin': 'Sign in',
          'forgot': 'Forgot Password?',
          'dontAccount': 'Don’t have an account? ',
          'alreadyAccount': 'Already have an account? ',
          'accept': 'By signing in, you accept ',
          'termsandservices': 'our terms of services ',
          'and': 'and ',
          'privacypolicy': '\nprivacy policy',
          'ForgotTitle': 'Forgot password',
          'ForgotBodyText':
              'Please enter your email address and\nwe will send you OTP for reset',
          'sendOtp': 'Send OTP',
          'otpTitle': 'OTP authentication',
          'otpBodyText': 'Enter verify code here',
          'otpButton': 'Verify OTP',
          'Update password': 'Update password',
          'Updatepasswordbody':
              'Your new password must be different\nfrom previous used password',
          'newPassword': 'New password',
          'confirmPassword': 'Confirm password',
          'Continue': 'Continue',
          'BusinessType': 'Select Business Type',
          'businessTypeBodyText':
              'Classify your business type based on industry, allowing for tailored strategies and targeted approaches.',
          'corporate': 'Corporate',
          'inividual': 'Individual',
          'Next': 'Next',
          'Organization information': 'Organization information',
          'Organization name': 'Organization name',
          'Enter organization address': 'Enter organization address',
          'Branch details': 'Branch details',
          'branchname': 'Enter main branch name',
          'address': 'Enter address',
          'number': 'Enter number',
          'enterEmail': 'Enter email',
          'managerDetails': 'Branch Manager Details',
          'enterName': 'Enter name',
          'Global Settings Configuration': 'Global Settings Configuration',
          'Select currency': 'Select currency',
          'Set time zone': 'Set time zone',
          'Tex rate': 'Tex rate',
          'Fiscal year start': 'Fiscal year start',
          'Contact details': 'Contact details',
          'Owner name': 'Owner name',
          'ownerHandler': 'If owner is handler don’t need to fill it',
          'Handler name': 'Handler name',
          'Restaurant/Cafe': 'Restaurant/Cafe',
          'Retailer': 'Retailer',
          'Wine Shop/Bar': 'Wine Shop/Bar',
          'Select business type': 'Select business type',

        },
      };
}
