// ignore_for_file: file_names

import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'signInTitle': 'Let’s sign you in',
          'signUpTitle': 'Let’s sign up',
          'signInButton': 'Login',
          'email': 'Email',
          'passwrod': 'Password',
          'signup': 'Sign up',
          'signin': 'Sign in',
          'forgot': 'Forgot Password?',
          'dontAccount': 'Don’t have an account? ',
          'alreadyAccount': 'Already have an account? ',
          'accept': 'By signing in, you accept ',
          'termsandservices': 'our terms of services ',
          'and': 'and ',
          'privacypolicy': '\nprivacy policy',
          'ForgotTitle': 'Forgot password',
          'ForgotBodyText':
              'Please enter your email address and\nwe will send you OTP for reset',
          'sendOtp': 'Send OTP',
          'otpTitle': 'OTP authentication',
          'otpBodyText': 'Enter verify code here',
          'otpButton': 'Verify OTP',
          'Update password': 'Update password',
          'Updatepasswordbody':
              'Your new password must be different\nfrom previous used password',
          'newPassword': 'New password',
          'confirmPassword': 'Confirm password',
          'Continue': 'Continue',
          'BusinessType': 'Select Business Type',
          'businessTypeBodyText':
              'Classify your business type based on industry, allowing for tailored strategies and targeted approaches.',
          'corporate': 'Corporate',
          'inividual': 'Individual',
          'Next': 'Next',
          'Organization information': 'Organization information',
          'Organization name': 'Organization name',
          'Enter organization address': 'Enter organization address',
          'Branch details': 'Branch details',
          'branchname': 'Enter main branch name',
          'address': 'Enter address',
          'number': 'Enter number',
          'enterEmail': 'Enter email',
          'managerDetails': 'Branch Manager Details',
          'enterName': 'Enter name',
          'Global Settings Configuration': 'Global Settings Configuration',
          'Select currency': 'Select currency',
          'Set time zone': 'Set time zone',
          'Tax rate': 'Tax rate',
          'Fiscal year start': 'Fiscal year start',
          'Contact details': 'Contact details',
          'Owner name': 'Owner name',
          'ownerHandler': 'If owner is handler don’t need to fill it',
          'Handler name': 'Handler name',
          'Restaurant/Cafe': 'Restaurant/Cafe',
          'Retailer': 'Retailer',
          'Wine Shop/Bar': 'Wine Shop/Bar',
          'Select business type': 'Select business type',
          'Dashboard': 'Dashboard',
          'Prime category': 'Prime category',
          'Subcategory': 'Subcategory',
          'Products': 'Products',
          'Stock adjustment': 'Stock adjustment',
          'Product management': 'Product management',
          'Category management': 'Category management',
          'What are you looking for?': 'What are you looking for?',
          'Add category': 'Add category',
          'Add new prime category': 'Add new prime category',
          'Category name': 'Category name',
          'Description': 'Description',
          'Maximum file size 50mb': 'Maximum file size 50mb',
          'Drop your file here, or ': 'Drop your file here, or ',
          'Browse': 'Browse',
          'Add': 'Add',
          'Add subcategory': 'Add subcategory',
          'Add new subcategory': 'Add new subcategory',
          'Subcategory name': 'Subcategory name',
          'Add product': 'Add product',
          'Basic Product Details': 'Basic Product Details',
          'Product name': 'Product name',
          'Product Identification and Sourcing':
              'Product Identification and Sourcing',
          'Variant details': 'Variant details',
          'Stock management': 'Stock management',
          'Add stock': 'Add stock',
          'Threshold numbers': 'Threshold numbers',
          'Variant attributes': 'Variant attributes',
          'Select material': 'Select material',
          'Add color': 'Add color',
          'Expire date': 'Expire date',
          'Sales price': 'Sales price',
          'Supplier price': 'Supplier price',
          'Discount': 'Discount',
          'Current stock': 'Current stock',
          'Add manufacturer details': 'Add manufacturer details',
          'Pricing Details': 'Pricing Details',
          'Supplier Prices': 'Supplier Prices',
          'Cost price entry': 'Cost price entry',
          'Price visibility': 'Price visibility',
          'Margin Calculation': 'Margin Calculation',
        },
      };
}
